### ISSUE TITLE
Getting exception error on 5.6: setTrustedProxies() must be of the type integer, array given

### ISSUE THREAD

**Issue by lesaff** [fideloper/TrustedProxy#111]
Updated my 5.5 installation to 5.6 and got this exception error:

```
"Type error: Argument 2 passed to Symfony\Component\HttpFoundation\Request::setTrustedProxies() must be of the type integer, array given, called in /Users/rudy/Sites/<redacted>/vendor/fideloper/proxy/src/TrustProxies.php on line 54 ◀"
```

I don't actually have anything in my trustedproxies config file, just the default.

**Comment by fideloper** [comment]
Hi!

In these versions of Laravel, you don't need to publish the assets (such as the project's configuration file) since Laravel has this project built into it's own middleware. Best bet is:

1. Remove the trustedproxy config file from your `config` directory if it's there
2. Don't manually register the service provider - that will happen automatically
3. Update your laravel trusted proxy middleware to match the latest from 5.6: https://github.com/laravel/laravel/blob/master/app/Http/Middleware/TrustProxies.php#L22

**Comment by lesaff** [comment]
Step 3 did it for me. previously, `$headers` was defined as 
```
    protected $headers = [
        Request::HEADER_FORWARDED => 'FORWARDED',
        Request::HEADER_X_FORWARDED_FOR => 'X_FORWARDED_FOR',
        Request::HEADER_X_FORWARDED_HOST => 'X_FORWARDED_HOST',
        Request::HEADER_X_FORWARDED_PORT => 'X_FORWARDED_PORT',
        Request::HEADER_X_FORWARDED_PROTO => 'X_FORWARDED_PROTO',
    ];
```

Thanks again!
Rudy

**Comment by fideloper** [comment]
You’re welcome!

**Comment by ecgk** [comment]
Something weird is happening. In my local environment works fine. But in staging environment I get that error. And I've made all the changes you've described. 

Staging:
php artisan --version
Laravel Framework 5.7.9

Local: 
php artisan --version
Laravel Framework 5.7.9

Thanks

**Comment by fideloper** [comment]
Sounds likely that staging (or local!) need a composer update or composer
install run to get them up to the both set of base libraries.

**Comment by ecgk** [comment]
Ok. I will try that. Thanks.
