### ISSUE TITLE
Question - my nginx headers are not carried across and i am having to manually set them, is this right?

### ISSUE THREAD

**Issue by AKApumkin** [fideloper/TrustedProxy#128]
Hi there, so i had the previous versions of this module and no real issue. However since upgrading i can't get the security specific headers from my reverse proxy Nginx config to display on the request header. 

The update added the new format 

_app/http/Middleware/TrustProxies.php_
```
    /**
     * The headers that should be used to detect proxies.
     *
     * @var int
     */
    protected $headers = Request::HEADER_X_FORWARDED_ALL;
```

But none of the headers get displayed, usually i had to create an extra middleware function for X-frame-options, but now i have to do it for everything. I feel this is not correct and possibly insecure or i am missing something in a config option somewhere to retrieve these headers the same as before? 

_app/http/Middleware/MyCustomGetRequestHeaders.php_
```
    public function handle($request, Closure $next)
    {
        $response = $next($request);
        $response->header('X-Frame-Options', 'SAMEORIGIN');
        $response->header('Referrer-Policy', 'no-referrer-when-downgrade');
        $response->header('X-Content-Type-Options', 'nosniff');
        $response->header('X-XSS-Protection', '1; mode=block');
        $response->header('Strict-Transport-Security', 'max-age=31536000; includeSubDomains');
        $response->header('Content-Security-Policy', "style-src 'self'"); 
        return $response;
    }
```

The above outputs what i expect when i check the network request 

![security-headers](https://user-images.githubusercontent.com/13747102/69694689-a399b880-1114-11ea-9db8-40b21b6950bd.jpg)

**Comment by fideloper** [comment]
Hi!

There might be some confusion there but I'm not sure - can you share your relevant nginx config and let me know what headers you see in the network panel are part of the response vs the request?

**Comment by AKApumkin** [comment]
Hey, Thanks for getting back to me. 

here is the config for the headers, and the reverse proxy, i didn't include anything else, but its got a rerouting function for non http traffic and an SSL. As mentioned before this config has worked on previous versions of Laravel and Trusted proxy without the additional need of  custom middle-ware.

```
    add_header Feature-Policy "geolocation none;midi none;notifications none;push none;sync-xhr none;microphone none;camera none;magnetometer none;gyroscope none;speaker self;vibrate none;fullscreen self;payment none;";
    add_header X-Frame-Options DENY;
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Forwarded-Proto https;
    add_header X-Forwarded-Host mywebsite.com;
    add_header Content-Security-Policy "default-src https: data: 'unsafe-inline' 'unsafe-eval'" always;
    add_header 'Referrer-Policy' 'origin'; 
    add_header X-Upstream $upstream_addr always;

    location / {
            # remove unnecessary proxy headers
            proxy_hide_header X-Powered-By;
            proxy_hide_header X-Rewrite-URL;
            proxy_hide_header X-Original-URL;
 
            # proxy
            proxy_cookie_path / "/; secure";
            proxy_set_header Host mywebsite.com;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Forwarded-Host mywebsite.com;
            proxy_pass https://127.0.0.1; 
    }  
   
```

**Comment by fideloper** [comment]
So, overall, Trusted Proxy does't mess with headers at all.

It helps the underlying Symfony classes decide if it should ignore the request (incoming) `X-Forwarded-*` headers or not. There's nothing that changes / ignores / adjusts incoming or outgoing headers.

So I don't necessarily think this is a trusted proxy issue. 


A few other points: I think you're missing up a request vs response header.

**First**:
`[add_header](http://nginx.org/en/docs/http/ngx_http_headers_module.html#add_header)` in nginx will add headers to the RESPONSE, not to the REQUEST that PHP sees. (Note that there's a documented way to force those headers to always be added).

The items you have in the `add_header`  are things you'd typically see as part of the requests incoming from the client and is NOT stuff you typically send back to the client as part of the HTTP response.

Assuming your nginx config you sent me is the load balancer config, you should only need the `proxy_set_header` directives. for the `X-Forwarded-*` items. 

The `X-Frame-Options`, etc, items make sense with `add_header`, although you may want that config to be part of the response from the server being proxied to rather than coming from the load balancer.

**Second**:

I'm not sure why you're `proxy_pass`ing to `https://127.0.0.1`. I don't really understand how the traffic is flowing your proxies so I can't say if that's appropriate or not. Perhaps you're setting this up for some micro services? This almost seems like you're using Nginx to proxy a request to itself (but definitely let me know if you have some other setup).

Hope this helps get you on the right path!

**Comment by AKApumkin** [comment]
Thanks for getting back to me again.

After re-reading your original response i see i forgot to clarify that i was only after the response headers, and also you may be right that this might be an issue with my configuration of Nginx and not Trust proxy, so from my understanding the `add_header X-Upstream $upstream_addr always;` Directive with the use of 'always' should  carry across the headers through the proxy even if there is an error. However without the custom middleware to re-add them, its not carrying through. Not really an issue as the middleware serves its purpose to add the response headers that the client side sees.

For your second point, my mistake for not explaining, i use a dockerized version of Laravel, with a fixed private IP address, i just obfuscated it, however using localhost was probably also a bad choice on my part.

Thanks for the help in trying to pinpoint were the issue is, i will comment back after doing more research if i finally figure out where i went wrong.

**Comment by fideloper** [comment]
Gotcha!

Not sure exactly what's going on there! That seems like that X-Upstream should be seen in your browser in the response there (I'm assuming there's no other proxy there, however perhaps another proxy exists that is dropping the header?).

It looks like you're doing basically the right thing. You can reference https://github.com/h5bp/server-configs-nginx/tree/master/h5bp to see how they add security headers in their responses - perhaps it'll give you some extra info.
