### ISSUE TITLE
Support for Lumen?

### ISSUE THREAD

**Issue by oblomki** [fideloper/TrustedProxy#30]
Does TrustedProxy work for Lumen? How would I install it in the absence of the same config file structure, etc.?

**Comment by fideloper** [comment]
Great point, I'll have to check out what's involved! Since this uses middleware, it might be a matter of just hand-rolling some config, but I'll find out!

**Comment by wriggle** [comment]
The problem so far seems to be "Call to undefined function Fideloper\Proxy\config_path()" when I try to publish the config. Otherwise I think it's possible to get it working.

**Comment by GrahamCampbell** [comment]
Lumen does not support config publishing.

**Comment by dwightwatson** [comment]
Is that entirely true? Lumen allows you to manually publish the frameworks configuration to `/config` to override it if you need. I'm not sure if it works in this respect for packages as well.

Lumen's approach is to use the `env()` helper with the standard defaults as a fallback. I suppose this won't work here because the configuration options are a little more complex, and not just strings.

**Comment by fideloper** [comment]
That's true...
For Lumen I'd remove the option to over-ride the default headers, which would make it simple. Then I'd probably try to test the "proxies" config to see if it's a string instead of array, and then split it by comma (assuming the config would be a comma-separated list).

Sounds doable at first blush!

**Comment by vluzrmos** [comment]
#32 initial
