### ISSUE TITLE
NetMask

### ISSUE THREAD

**Issue by rodolphofreire** [fideloper/TrustedProxy#35]
I really liked your work with trusted proxies, but after investigating how symfony compare IP I found they use netmask for comparison.

So instead of use \* in your config, you can pass an ip 0.0.0.0/0 to accept any proxy.

or use netmask to validate any IP,

Eg.: this proxy 192.168.0.0/16 will validate any IP from 192.168.0.0 to 192.168.255.255

I suggest to put this info in your config.

**Comment by fideloper** [comment]
Hi, thanks!

So what the code here does is say "if it's character `*`, set the trusted proxy IP to whatever the client IP is" (check that out here: https://github.com/fideloper/TrustedProxy/blob/master/src/TrustProxies.php#L58-L67).

The * isn't getting passed directly to Symfony, but it's still a little bit of a hack in that I set the trusted proxy to the current IP, rather than set a netmask of `0.0.0.0/0`.

What I think I'll do is set the `0.0.0.0/0` netmask, but keep the * notation, which will let users keep using `*`, and of course they can all set a netmask themselves instead of the shorthand `*` this package uses.

Let me know if you can spot any issues with that.

Thanks again!

**Comment by fideloper** [comment]
That makes the internal API a tad cleaner too, here's the commit for that if you could review it for me as well? (get a second pair of eyes :D )

https://github.com/fideloper/TrustedProxy/commit/8e2f140f61898364a4b1a9a5db19429ae069b7bd

**Comment by GrahamCampbell** [comment]
I think is resolved then?

**Comment by fideloper** [comment]
I have it as a separate branch, might still add it in for use instead of `*` to denote "all addresses"
