### ISSUE TITLE
Two Ip Address for HTTP_X_FORWARDED_FOR

### ISSUE THREAD

**Issue by t202wes** [fideloper/TrustedProxy#46]
$_SERVER[HTTP_X_FORWARDED_FOR] => 73.175.54.69, 199.27.133.76

TrustProxy believes the client IP is the last one, 199.27.133.76, but the actual ip address is 73.170.54.69.

I'm using both CloudFlare CDN & AWS' Elastic Load Balancer.

My configuration is as follows:

'headers' => [
        \Illuminate\Http\Request::HEADER_CLIENT_IP    => 'X_FORWARDED_FOR',
        \Illuminate\Http\Request::HEADER_CLIENT_HOST  => 'X_FORWARDED_HOST',
        \Illuminate\Http\Request::HEADER_CLIENT_PROTO => 'X_FORWARDED_PROTO',
        \Illuminate\Http\Request::HEADER_CLIENT_PORT  => 'X_FORWARDED_PORT',
    ]

I assume I could just switch it to detect for this: [HTTP_CF_CONNECTING_IP] => 73.175.54.69, which is the header that cloudflare gives with the client IP. But sometimes I access the server without cloudflare, so I really need to get it from the X_FORWARDED_FOR value.

How do we fix this?

**Comment by tamc** [comment]
This only gives the incorrect result if using:
   
    'proxy' => '*'

Otherwise, it gives the result that Symphony intended (http://api.symfony.com/2.7/Symfony/Component/HttpFoundation/Request.html#method_getClientIps) where $request->getClientIps() returns the most trusted IP first, and the least trusted IP last. The $request->getClientIp() then returns the first of these, the most trusted client IP.

IMO, the correct behaviour for 'proxy' => '*' would be for all the proxies in X-Forwarded-For to be counted as trusted, and therefore for $request->getClientIps() to return a single IP (the end client IP) and therefore $request->getClientIp() to return the IP address expected in this issue.

**Comment by tamc** [comment]
A workaround is to use:

    'proxy' => ['0.0.0.0/0', '2000:0:0:0:0:0:0:0/3']

The first trusts all IPV4 addresses, the second trusts all currently allocated IPV6 addresses.
