### ISSUE TITLE
Behind Amazon Beanstalk, not giving me the right ip

### ISSUE THREAD

**Issue by newtonianb** [fideloper/TrustedProxy#7]
I just tried this on an amazon beanstalk configuration, proxy is set to *. The issue is when I run Request::getClientIp() I get  10.107.15.71 but my client ip is really 203.61.26.1 so it's returning me this other IP I'm not sure what it is.

**Comment by fideloper** [comment]
@benswinburne it's worth noting that the Header sent as "X-Forwarded_Proto" will actually become `HTTP_X_FORWARDED_PROTO` in PHP (and thus in Symfony's `Request` class).

However, this is still a great suggestion. I think HAProxy in particular uses `X-Forwarded-Scheme` instead of the expected `X-Forwarded-Proto` header, for example. (See #9)

**Comment by fideloper** [comment]
Also, functionality added in update to package on develop branch, ready for when Laravel 5 comes out,

Thanks again for the pointer in the direction of `setTrustedHeaderName` !
